-- ENTERING SQUAD DETAILS

USE worldcup2022;

SELECT  * FROM SquadDetails;

CREATE TABLE SquadDetails (
    unique_no INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nation VARCHAR(75),
    age INT,
    player_name VARCHAR(75),
    football_club VARCHAR(75),
    country_league VARCHAR(75)
);

INSERT INTO SquadDetails (unique_no, nation, age, player_name, football_Club, country_league)
VALUES 

INSERT INTO SquadDetails (unique_no, nation, age, player_name, football_club, country_league)
VALUES 


INSERT INTO SquadDetails
  (unique_no,nation,age,player_name,football_club,country_league)
VALUES
(1, 'Brazil', 30, 'Alisson Becker', 'Liverpool', 'England'),
(2,'Brazil',34,'Weverton Pereira','Palmeiras','Brazil'),
  (3,'Brazil',29,'Ederson Moraes','Manchester City ','England'),
  (4,'Brazil',38,'Thiago Silva','Chelsea ','England'),
  (5,'Brazil',28,'Marquinhos','Paris Saint-Germain ','France'),
  (6,'Brazil',24,'Éder Militão','Real Madrid ','Spain'),
  (7,'Brazil',25,'Gleison Bremer','Juventus ','Italy'),
  (8,'Brazil',31,'Danilo Luiz da Silva','Juventus ','Italy'),
  (9,'Brazil',39,'Dani Alves','UNAM ','Mexico'),
  (10,'Brazil',31,'Alex Sandro','Juventus ','Italy'),
  (11,'Brazil',29,'Alex Telles','Sevilla ','Spain'),
  (12,'Brazil',30,'Casemiro','Manchester United ','England'),
  (13,'Brazil',25,'Lucas Paquetá','West Ham United ','England'),
  (14,'Brazil',29,'Fred','Manchester United ','England'),
  (15,'Brazil',29,'Fabinho','Liverpool ','England'),
  (16,'Brazil',24,'Bruno Guimarães','Newcastle United ','England'),
  (17,'Brazil',25,'Éverton Ribeiro','Flamengo ','Brazil'),
  (18,'Brazil',21,'Gabriel Martinelli','Arsenal ','England'),
  (19,'Brazil',30,'Neymar da Silva','Paris Saint-Germain ','France'),
  (20,'Brazil',22,'Vinícius Júnior','Real Madrid ','Spain'),
  (21,'Brazil',22,'Antony Matheus','Manchester United ','England'),
  (22,'Brazil',25,'Raphinha','Barcelona ','Spain'),
  (23,'Brazil',25,'Richarlison','Tottenham Hotspur ','England'),
  (24,'Brazil',25,'Gabriel Jesus','Arsenal ','England'),
  (25,'Brazil',21,'Rodrygo','Real Madrid ','Spain'),
  (26,'Brazil',25,'Pedro Guilherme','Flamengo ','Brazil'),
  (27,'Costa Rica',35,'Keylor Navas','Paris Saint-Germain ','France'),
  (28,'Costa Rica',33,'Esteban Alvarado','CS Herediano ','Costa Rica'),
  (29,'Costa Rica',23,'Patrick Sequeira','Deportivo Lugo ','Spain'),
  (30,'Costa Rica',30,'Francisco Calvo','Konyaspor ','Turkey'),
  (31,'Costa Rica',32,'Bryan Oviedo','Real Salt Lake ','USA'),
  (32,'Costa Rica',33,'Oscar Duarte','Al Wehda ','Saudi Arabia'),
  (33,'Costa Rica',34,'Kendall Waston','Deportivo Saprissa ','Costa Rica'),
  (34,'Costa Rica',28,'Ronald Matarrita','FC Cincinnati ','USA'),
  (35,'Costa Rica',28,'Keysher Fuller','CS Herediano ','Costa Rica'),
  (36,'Costa Rica',27,'Juan Pablo Vargas','Millonarios ','Colombia'),
  (37,'Costa Rica',23,'Carlos Martinez','San Carlos ','Costa Rica'),
  (38,'Costa Rica',34,'Celso Borges','Alajuelense ','Costa Rica'),
  (39,'Costa Rica',37,'Bryan Ruiz','Alajuelense ','Costa Rica'),
  (40,'Costa Rica',30,'Yeltsin Tejeda','CS Herediano ','Costa Rica'),
  (41,'Costa Rica',25,'Gerson Torres','CS Herediano ','Costa Rica'),
  (42,'Costa Rica',18,'Jewison Bennette','Sunderland ','England'),
  (43,'Costa Rica',21,'Daniel Chacon','Colorado Rapids ','USA'),
  (44,'Costa Rica',26,'Youstin Salas','Deportivo Saprissa ','Costa Rica'),
  (45,'Costa Rica',20,'Roan Wilson','Municipal Grecia ','Costa Rica'),
  (46,'Costa Rica',19,'Brandon Aguilera','Nottingham Forest ','England'),
  (47,'Costa Rica',24,'Douglas Lopez','CS Herediano ','Costa Rica'),
  (48,'Costa Rica',21,'Anthony Hernandez','Puntarenas ','Costa Rica'),
  (49,'Costa Rica',21,'Alvaro Zamora','Deportivo Saprissa ','Costa Rica'),
  (50,'Costa Rica',30,'Joel Campbell','Club Leon ','Mexico'),
  (51,'Costa Rica',33,'Johan Venegas','Alajuelense ','Costa Rica'),
  (52,'Costa Rica',22,'Anthony Contreras','CS Herediano ','Costa Rica'),
  (53,'Japan',33,'Shuichi Gonda','Shimizu S-Pulse','Japan'),
  (54,'Japan',30,'Daniel Schmidt','Sint-Truiden','Belgium'),
  (55,'Japan',39,'Eiji Kawashima','Strasbourg ','France'),
  (56,'Japan',34,'Maya Yoshida','Schalke ','Germany'),
  (57,'Japan',23,'Takehiro Tomiyasu','Arsenal ','England'),
  (58,'Japan',31,'Shogo Taniguchi','Kawasaki Frontale ','Japan'),
  (59,'Japan',25,'Ko Itakura','Borussia Mönchengladbach ','Germany'),
  (60,'Japan',23,'Hiroki Ito','Stuttgart ','Germany'),
  (61,'Japan',36,'Yuto Nagatomo','FC Tokyo ','Japan'),
  (62,'Japan',25,'Yuta Nakayama','Huddersfield Town ','England'),
  (63,'Japan',28,'Miki Yamane','Kawasaki Frontale ','Japan'),
  (64,'Japan',32,'Hiroki Sakai','Urawa Reds ','Japan'),
  (65,'Japan',29,'Wataru Endo','Stuttgart ','Germany'),
  (66,'Japan',27,'Hidemasa Morita','Sporting Cp','Portugal'),
  (67,'Japan',25,'Ao Tanaka','Fortuna Dusseldorf ','Germany'),
  (68,'Japan',30,'Gaku Shibasaki','Leganes ','Spain'),
  (69,'Japan',25,'Kaoru Mitoma','Brighton & Hove Albion ','England'),
  (70,'Japan',26,'Daichi Kamada','Eintracht Frankfurt ','Germany'),
  (71,'Japan',24,'Ritsu Doan','Freiburg ','Germany'),
  (72,'Japan',29,'Junya Ito','Reims ','France'),
  (73,'Japan',27,'Takumi Minamino','AS Monaco ','France'),
  (74,'Japan',21,'Takefusa Kubo','Real Sociedad ','Spain'),
  (75,'Japan',25,'Yuki Soma','Nagoya Grampus ','Japan'),
  (76,'Japan',25,'Daizen Maeda','Glasgow Celtic ','Scotland'),
  (77,'Japan',27,'Takuma Asano','Bochum ','Germany'),
  (78,'Japan',24,'Ayase Ueda','Club Brugge ','Belgium'),
  (79,'Denmark',36,'Kasper Schmeichel','Nice ','France'),
  (80,'Denmark',23,'Oliver Christensen','Hertha Berlin ','Germany'),
  (81,'Denmark',33,'Simon Kjær','AC Milan ','Italy'),
  (82,'Denmark',25,'Joakim Mæhle','Atalanta ','Italy'),
  (83,'Denmark',25,'Rasmus Nissen Kristensen','Leeds United ','England'),
  (84,'Denmark',33,'Daniel Wass','Brondby FK ','Denmark'),
  (85,'Denmark',31,'Jens Stryger Larsen','Trabzonspor ','Turkey'),
  (86,'Denmark',26,'Andreas Christensen','Barcelona ','Spain'),
  (87,'Denmark',26,'Joachim Andersen','Crystal Palace ','England'),
  (88,'Denmark',24,'Victor Nelsson','Galatasaray ','Turkey'),
  (89,'Denmark',26,'Mathias Jensen','Brentford ','England'),
  (90,'Denmark',27,'Pierre-emile Højbjerg','Tottenham Hotspur ','England'),
  (91,'Denmark',31,'Thomas Delaney','Sevilla ','Spain'),
  (92,'Denmark',30,'Christian Eriksen','Manchester United ','England'),
  (93,'Denmark',25,'Kasper Dolberg','Sevilla ','Spain'),
  (94,'Denmark',22,'Andreas Skov Olsen','Club Brugge ','Belgium'),
  (95,'Denmark',29,'Andreas Cornelius','Copenhagen ','Denmark'),
  (96,'Denmark',23,'Jonas Wind','VfL Wolfsburg ','Germany'),
  (97,'Denmark',31,'Martin Braithwaite','Espanyol ','Spain'),
  (98,'Denmark',22,'Jesper Lindstrøm','Eintracht Frankfurt ','Germany'),
  (99,'Denmark',22,'Mikkel Damsgaard','Brentford ','England'),
  (100,'Australia',30,'Mathew Ryan','Copenhagen ','Denmark'),
  (101,'Australia',37,'Danny Vukovic','Central Coast ','Australia'),
  (102,'Australia',33,'Andrew Redmayne','Sydney FC ','Australia'),
  (103,'Australia',32,'Aziz Behich','Dundee United ','Scotland'),
  (104,'Australia',23,'Nathaniel Atkinson','Hearth of Midlothian ','Scotland'),
  (105,'Australia',28,'Milos Degenek','Colombus Crew ','USA'),
  (106,'Australia',30,'Bailey Wright','Sunderland ','England'),
  (107,'Australia',26,'Fran Karacic','Brescia ','Italy'),
  (108,'Australia',24,'Kye Rowles','Hearth of Midlothian ','Scotland'),
  (109,'Australia',24,'Harry Souttar','Stoke City ','England'),
  (110,'Australia',22,'Joel King','Odense Boldklub ','Denmark'),
  (111,'Australia',25,'Thomas Deng','Albirex Niigata ','Japan'),
  (112,'Australia',32,'Aaron Mooy','Celtic ','Scotland'),
  (113,'Australia',26,'Ajdin Hrustic','Hellas Verona ','Italy'),
  (114,'Australia',29,'Jackson Irvine','St Pauli ','Germany'),
  (115,'Australia',24,'Riley Mcgree','Middlesbrough ','England'),
  (116,'Australia',24,'Cameron Devlin','Hearth of Midlothian ','Scotland'),
  (117,'Australia',29,'Martin Boyle','Hibernian ','Scotland'),
  (118,'Australia',27,'Jason Cummings','Central Coast ','Australia'),
  (119,'Australia',31,'Mitchell Duke','Fagiano Okayama ','Japan'),
  (120,'Australia',30,'Craig Goodwin','Adelaide United ','Australia'),
  (121,'Australia',18,'Garang Kuol','Central Coast ','Australia'),
  (122,'Australia',31,'Mathew Leckie','Melbourne City ','Australia'),
  (123,'Australia',27,'Awer Mabil','Cadiz ','Spain'),
  (124,'Australia',29,'Jamie Maclaren','Melbourne City ','Australia'),
  (125,'Croatia',27,'Dominik Livakovic','Dinamo Zagreb ','Croatia'),
  (126,'Croatia',27,'Ivica Ivusic','NK Osijek ','Croatia'),
  (127,'Croatia',26,'Ivo Grbic','Atlético Madrid ','Spain'),
  (128,'Croatia',33,'Domagoj Vida','AEK Athens ','Greece'),
  (129,'Croatia',33,'Dejan Lovren','Zenit Saint Petersburg ','Russia'),
  (130,'Croatia',29,'Borna Barisic','Rangers ','Scotland'),
  (131,'Croatia',27,'Josip Juranovic','Celtic ','Scotland'),
  (132,'Croatia',20,'Josko Gvardiol','RB Leipzig ','Germany'),
  (133,'Croatia',24,'Borna Sosa','VfB Stuttgart ','Germany'),
  (134,'Croatia',22,'Josip Stanisic','Bayern Munchen ','Germany'),
  (135,'Croatia',24,'Martin Erlic','Sassuolo ','Italy'),
  (136,'Croatia',22,'Josip Sutalo','Dinamo Zagreb ','Croatia'),
  (137,'Croatia',37,'Luka Modric','Real Madrid ','Spain'),
  (138,'Croatia',28,'Mateo Kovacic','Chelsea ','England'),
  (139,'Croatia',29,'Marcelo Brozovic','Inter Milan ','Italy'),
  (140,'Croatia',27,'Mario Pasalic','Atalanta ','Italy'),
  (141,'Croatia',25,'Nikola Vlasic','Torino ','Italy'),
  (142,'Croatia',24,'Lovro Majer','Rennes ','France'),
  (143,'Croatia',25,'Kristijan Jakic','Eintracht Frankfurt ','Germany'),
  (144,'Croatia',20,'Luka Sucic','Red Bull Salzburg ','Austria'),
  (145,'Croatia',33,'Ivan Perisic','Tottenham Hotspur ','England'),
  (146,'Croatia',31,'Andrej Kramaric','1899 Hoffenheim ','Germany'),
  (147,'Croatia',28,'Bruno Petkovic','Dinamo Zagreb ','Croatia'),
  (148,'Croatia',29,'Mislav Orsic','Dinamo Zagreb ','Croatia'),
  (149,'Croatia',31,'Ante Budimir','Osasuna ','Spain'),
  (150,'Croatia',29,'Marko Livaja','Hajduk Split ','Croatia'),
  (151,'Switzerland',33,'Yann Sommer','Borussia Mönchengladbach ','Germany'),
  (152,'Switzerland',28,'Jonas Omlin','Montpellier ','France'),
  (153,'Switzerland',24,'Gregor Kobel','Borussia Dortmund ','Germany'),
  (154,'Switzerland',24,'Philipp Köhn','Red Bull Salzburg ','Austria'),
  (155,'Switzerland',30,'Ricardo Rodriguez','Torino ','Italy'),
  (156,'Switzerland',30,'Fabian Schär','Newcastle United ','England'),
  (157,'Switzerland',27,'Manuel Akanji','Manchester City ','England'),
  (158,'Switzerland',26,'Nico Elvedi','Borussia Mönchengladbach ','Germany'),
  (159,'Switzerland',29,'Silvan Widmer','Mainz 05 ','Germany'),
  (160,'Switzerland',24,'Eray Cömert','Valencia ','Spain'),
  (161,'Switzerland',31,'Xherdan Shaqiri','Chicago Fire ','USA'),
  (162,'Switzerland',30,'Granit Xhaka','Arsenal ','England'),
  (163,'Switzerland',30,'Remo Freuler','Nottingham Forest ','England'),
  (164,'Switzerland',25,'Denis Zakaria','Chelsea ','England'),
  (165,'Switzerland',25,'Djibril Sow','Eintracht Frankfurt ','Germany'),
  (166,'Switzerland',31,'Renato Steffen','Lugano ','Switzerland'),
  (167,'Switzerland',26,'Edimilson Fernandes','Mainz 05 ','Germany'),
  (168,'Switzerland',33,'Fabian Frei','Basel ','Switzerland'),
  (169,'Switzerland',25,'Michel Aebischer','Bologna ','Italy'),
  (170,'Switzerland',20,'Ardon Jashari','Luzern ','Switzerland'),
  (171,'Switzerland',20,'Fabian Rieder','Young Boys ','Switzerland'),
  (172,'Switzerland',30,'Haris Seferovic','Galatasaray ','Turkey'),
  (173,'Switzerland',25,'Breel Embolo','AS Monaco ','France'),
  (174,'Switzerland',24,'Ruben Vargas FC','Augsburg ','France'),
  (175,'Switzerland',28,'Christian Fassnacht','Young Boys ','Turkey'),
  (176,'Switzerland',22,'Noah Okafor','Red Bull Salzburg ','Austria'),
  (177,'France',35,'Hugo Lloris','Tottenham Hotspur ','England'),
  (178,'France',37,'Steve Mandanda','Rennes ','France'),
  (179,'France',29,'Alphonse Areola','West Ham United ','England'),
  (180,'France',23,'Ibrahima Konaté','Liverpool ','England'),
  (181,'France',26,'Benjamin Pavard','Bayern Munchen ','Germany'),
  (182,'France',23,'Jules Koundé','Barcelona ','Spain'),
  (183,'France',21,'William Saliba','Arsenal ','England'),
  (184,'France',26,'Lucas Hernandez','Bayern Munchen ','Germany'),
  (185,'France',25,'Theo Hernandez','AC Milan ','Italy'),
  (186,'France',27,'Presnel Kimpembe','Paris Saint-Germain ','France'),
  (187,'France',24,'Dayot Upamecano','Bayern Munchen ','Germany'),
  (188,'France',29,'Rapael Varane','Manchester United ','England'),
  (189,'France',22,'Aurélien Tchouaméni','Real Madrid ','Spain'),
  (190,'France',29,'Jordan Veretout','Marseille ','France'),
  (191,'France',27,'Adrien Rabiot','Juventus ','Italy'),
  (192,'France',23,'Matteo Guendouzi','Marseille ','France'),
  (193,'France',19,'Eduardo Camavinga','Real Madrid ','Spain'),
  (194,'France',23,'Youssouf Fofana','Monaco ','France'),
  (195,'France',31,'Antoine Griezmann','Atlético Madrid ','Spain'),
  (196,'France',36,'Olivier Giroud','AC Milan ','Italy'),
  (197,'France',25,'Ousmane Dembélé','Barcelona ','Spain'),
  (198,'France',23,'Kylian Mbappé','Paris Saint-Germain ','France'),
  (199,'France',34,'Karim Benzema','Real Madrid ','Spain'),
  (200,'France',24,'Christopher Nkunku','RB Leipzig ','Germany'),
  (201,'France',26,'Kingsley Coman','Bayern Munchen ','Germany'),
  (202,'USA',27,'Ethan Horvath','Luton Town ','England'),
  (203,'USA',33,'Sean Johnson','New York City FC ','USA'),
  (204,'USA',28,'Matt Turner','Arsenal ','England'),
  (205,'USA',24,'Cameron Carter-Vickers','Celtic ','Scotland'),
  (206,'USA',22,'Sergino Dest','AC Milan ','Italy'),
  (207,'USA',30,'Aaron Long','New York Red Bulls ','USA'),
  (208,'USA',26,'Shaq Moore','Nashville SC ','USA'),
  (209,'USA',35,'Tim Ream','Fulham ','England'),
  (210,'USA',25,'Antonee Robinson','Fulham ','England'),
  (211,'USA',19,'Joe Scally','Borussia Mönchengladbach ','Germany'),
  (212,'USA',29,'Walker Zimmerman','Nashville SC ','USA'),
  (213,'USA',29,'Deandre Yedlin','Inter Miami CF ','USA'),
  (214,'USA',22,'Brenden Aaronson','Leeds United ','England'),
  (215,'USA',27,'Kellyn Acosta','LA Galaxy ','USA'),
  (216,'USA',23,'Tyler Adams','Leeds United ','England'),
  (217,'USA',24,'Luca De La Torre','Celta De Vigo ','Spain'),
  (218,'USA',24,'Weston Mckennie','Juventus ','Italy'),
  (219,'USA',19,'Yunus Musah','Valencia ','Spain'),
  (220,'USA',27,'Cristian Roldan','Seattle Sounders ','USA'),
  (221,'USA',24,'Christian Pulisik','Chelsea ','England'),
  (222,'USA',21,'Jesús Ferreira','FC Dallas ','USA'),
  (223,'USA',28,'Jordan Morris','Seattle Sounders ','USA'),
  (224,'USA',19,'Giovanni Reyna','Borussia Dortmund ','Germany'),
  (225,'USA',22,'Josh Sargent','Norwich City ','England'),
  (226,'USA',22,'Timothy Weah','Lille ','France'),
  (227,'USA',24,'Haji Wright','Antalyaspor ','Turkey'),
  (228,'Wales',35,'Wayne Hennessey','Nottingham Forest ','England'),
  (229,'Wales',29,'Danny Ward','Leicester City ','England'),
  (230,'Wales',30,'Adam Davies','Sheffield United ','England'),
  (231,'Wales',29,'Ben Davies','Tottenham Hotspur ','England'),
  (232,'Wales',22,'Ethan Ampadu','Spezia ','Italy'),
  (233,'Wales',21,'Neco Williams','Nottingham Forest ','England'),
  (234,'Wales',29,'Ben Cabango','Swansea City ','England'),
  (235,'Wales',27,'Tomm Lockyer','Luton Town ','England'),
  (236,'Wales',25,'Joe Rodon','Rennes ','France'),
  (237,'Wales',25,'Chris Mephan','Bournemouth ','England'),
  (238,'Wales',33,'Chris Gunter','AFC Wimbledon ','England'),
  (239,'Wales',27,'Connor Roberts','Burnley ','England'),
  (240,'Wales',31,'Aaron Ramsey','Nice ','France'),
  (241,'Wales',25,'Joe Allen','Swansea City ','England'),
  (242,'Wales',21,'Dylan Levitt','Dundee United ','Scotland'),
  (243,'Wales',23,'Sorba Thomas','Huddersfield Town ','England'),
  (244,'Wales',25,'Harry Wilson','Fulham ','England'),
  (245,'Wales',22,'Matthew Smith','MK Dons ','England'),
  (246,'Wales',25,'Joe Morrell','Portsmouth ','England'),
  (247,'Wales',29,'Jonny Williams','Swindon City ','England'),
  (248,'Wales',20,'Rubin Colwill','Cardiff City ','England'),
  (249,'Wales',33,'Gareth Bale','LA Galaxy ','USA'),
  (250,'Wales',30,'Kieffer Moore','Bournemouth ','England'),
  (251,'Wales',23,'Mark Harris','Cardiff City ','England'),
  (252,'Wales',21,'Brennan Johnson','Nottingham Forest ','England'),
  (253,'Wales',25,'Daniel James','Fulham ','England'),
  (254,'Cameroon',26,'Andre Onana','Inter Milan ','Italy'),
  (255,'Cameroon',29,'Devis Epassy','Abha Club ','Saudi Arabia'),
  (256,'Cameroon',19,'Simon Ngapandouetnbu','Marseille ','France'),
  (257,'Cameroon',23,'Enzo Ebosse','Udinese ','Italy'),
  (258,'Cameroon',25,'Nouhou Tolo','Seattle Sounders ','USA'),
  (259,'Cameroon',27,'Jean-Charles Castelletto','Nantes ','France'),
  (260,'Cameroon',21,'Christopher Wooh','Rennes ','France'),
  (261,'Cameroon',25,'Olivier Mbaizo','Philadelphia ','USA'),
  (262,'Cameroon',29,'Collins Fai','Al-Tai ','Saudi Arabia'),
  (263,'Cameroon',32,'Nicolas Nkoulou','Aris Thessaloniki ','Greece'),
  (264,'Cameroon',26,'Zambo Anguissa','Napoli ','Italy'),
  (265,'Cameroon',25,'Samuel Gouet','KV Mechelen ','Belgium'),
  (266,'Cameroon',27,'Pierre Kunde','Olympiacos ','Greece'),
  (267,'Cameroon',24,'Martin Hongla','Hellas Verona ','Italy'),
  (268,'Cameroon',27,'Gaël Ondoua','Hannover ','Germany'),
  (269,'Cameroon',26,'Olivier Ntcham','Swansea City ','England'),
  (270,'Cameroon',24,'Gerome Ngom','Colombe Dja ','Cameroon'),
  (271,'Cameroon',33,'Eric Choupo-Moting','Bayern Munchen ','Germany'),
  (272,'Cameroon',30,'Karl Toko Ekambi','Lyon ','France'),
  (273,'Cameroon',30,'Vincent Aboubakar','Al- Nassr ','Saudi Arabia'),
  (274,'Cameroon',23,'Bryan Mbeumo','Brentford ','England'),
  (275,'Cameroon',29,'Jean-Pierre Nsame','Young Boys ','Switzerland'),
  (276,'Cameroon',28,'Moumi Ngamaleu','Dynamo Moscow ','Russia'),
  (277,'Cameroon',27,'Georges-Kévin Nkoudou','Besiktas ','Turkey'),
  (278,'Cameroon',27,'Christian Bassogog','Shanghai Shenhua ','China'),
  (279,'Cameroon',21,'Souaibou Marou','Coton Sport ','Cameroon'),
  (280,'Germany',36,'Manuel Neuer','Bayern Munchen ','Germany'),
  (281,'Germany',30,'Marc-André ter Stegen','Barcelona ','Spain'),
  (282,'Germany',32,'Kevin Trapp','Eintracht Frankfurt ','Germany'),
  (283,'Germany',20,'Armel Bella Kotchap','Southampton ','England'),
  (284,'Germany',28,'Matthias Ginter','SC Freiburg ','Germany'),
  (285,'Germany',29,'Christian Gunter','SC Freiburg ','Germany'),
  (286,'Germany',26,'Thilo Kehrer','West Ham United ','England'),
  (287,'Germany',26,'Lukas Klostermann','RB Leipzig ','Germany'),
  (288,'Germany',24,'David Raum','RB Leipzig ','Germany'),
  (289,'Germany',29,'Antonio Rudiger','Real Madrid ','Spain'),
  (290,'Germany',22,'Nico Schlotterbeck','Borussia Dortmund ','Germany'),
  (291,'Germany',27,'Niklas Sule','Borussia Dortmund ','Germany'),
  (292,'Germany',26,'Julian Brandt','Borussia Dortmund ','Germany'),
  (293,'Germany',27,'Serge Gnabry','Bayern Munchen ','Germany'),
  (294,'Germany',27,'Leon Goretzka','Bayern Munchen ','Germany'),
  (295,'Germany',30,'Mario Gotze','Eintracht Frankfurt ','Germany'),
  (296,'Germany',32,'Ilkay Gundo?an','Manchester City ','England'),
  (297,'Germany',30,'Jonas Hofmann','Borussia Mönchengladbach ','Germany'),
  (298,'Germany',27,'Joshua Kimmich','Bayern Munchen ','Germany'),
  (299,'Germany',19,'Jamal Musiala','Bayern Munchen ','Germany'),
  (300,'Germany',20,'Karim Adeyemi','Borussia Dortmund ','Germany'),
  (301,'Germany',29,'Niclas Füllkrug','SV Werder Bremen ','Germany'),
  (302,'Germany',23,'Kai Havertz','Chelsea ','England'),
  (303,'Germany',17,'Youssoufa Moukoko','Borussia Dortmund ','Germany'),
  (304,'Germany',33,'Thomas Muller','Bayern Munchen ','Germany'),
  (305,'Germany',26,'Leroy Sané','Bayern Munchen ','Germany'),
  (306,'Belgium',30,'Thibaut Courtois','Real Madrid ','Spain'),
  (307,'Belgium',34,'Simon Mignolet','Club Brugge ','Belgium'),
  (308,'Belgium',30,'Koen Casteels','VfL Wolfsburg ','Germany'),
  (309,'Belgium',35,'Jan Vertonghen','Anderlecht ','Belgium'),
  (310,'Belgium',33,'Toby Alderweireld','Royal Antwerp ','Belgium'),
  (311,'Belgium',27,'Leander Dendoncker','Wolverhampton Wanderers ','England'),
  (312,'Belgium',24,'Wout Faes','Leicester City ','England'),
  (313,'Belgium',22,'Arthur Theate','Rennes ','France'),
  (314,'Belgium',19,'Zeno Debast','Anderlecht ','Belgium'),
  (315,'Belgium',29,'Yannick Carrasco','Atlético Madrid ','Spain'),
  (316,'Belgium',31,'Thomas Meunier','Borussia Dortmund ','Germany'),
  (317,'Belgium',26,'Timothy Castagne','Leicester City ','England'),
  (318,'Belgium',29,'Thorgan Hazard','Borussia Dortmund ','Germany'),
  (319,'Belgium',31,'Kevin De Bruyne','Manchester City ','England'),
  (320,'Belgium',25,'Youri Tielemans','Leicester City ','England'),
  (321,'Belgium',21,'Amadou Onana','Everton ','England'),
  (322,'Belgium',33,'Axel Witsel','Atlético Madrid ','Spain'),
  (323,'Belgium',30,'Hans Vanaken','Club Brugge ','Belgium'),
  (324,'Belgium',31,'Eden Hazard','Real Madrid ','Spain'),
  (325,'Belgium',21,'Charles De Ketelaere','AC Milan ','Italy'),
  (326,'Belgium',27,'Leandro Trossard','Brighton & Hove Albion ','England'),
  (327,'Belgium',35,'Dries Mertens','Galatasaray ','Turkey'),
  (328,'Belgium',20,'Jérémy Doku','Rennes ','France'),
  (329,'Belgium',29,'Romelu Lukaku','Inter Milan ','Italy'),
  (330,'Belgium',29,'Michy Batshuayi','Fenerbahçe ','Turkey'),
  (331,'Belgium',22,'Loïs Openda','Lens ','France'),
  (332,'Morocco',32,'Yassine Bounou','Sevilla ','Spain'),
  (333,'Morocco',33,'Munir Mohand Mohamedi','Al Wehda ','Saudi Arabia'),
  (334,'Morocco',26,'Ahmed Reda Tagnaouti','Wydad AC ','Morocco'),
  (335,'Morocco',24,'Achraf Hakimi','Paris Saint-Germain ','France'),
  (336,'Morocco',24,'Noussair Mazraoui','Bayern Munchen ','Germany'),
  (337,'Morocco',26,'Nayef Aguerd','West Ham United ','England'),
  (338,'Morocco',32,'Ghanem Saïss','Wolverhampton Wanderers ','England'),
  (339,'Morocco',23,'Achraf Dari','Stade Brestois ','France'),
  (340,'Morocco',30,'Jawad El Yamiq','Real Valladolid ','Spain'),
  (341,'Morocco',27,'Yahya Attiat Allah','Wydad AC ','Morocco'),
  (342,'Morocco',29,'Badr Benoun','Qatar SC ','Qatar'),
  (343,'Morocco',26,'Sofyan Amrabat','Fiorentina ','Italy'),
  (344,'Morocco',25,'Abdelhamid Sabri','Sampdoria ','Italy'),
  (345,'Morocco',25,'Selim Amallah','Standard Liège ','Belgium'),
  (346,'Morocco',22,'Azzedine Ounahi','Angers SCO ','France'),
  (347,'Morocco',18,'Bilal El Khannouss','K.R.C. Genk ','Belgium'),
  (348,'Morocco',31,'Yahya Jabrane','Wydad AC ','Morocco'),
  (349,'Morocco',29,'Hakim Ziyech','Chelsea ','England'),
  (350,'Morocco',29,'Sofiane Boufal','Angers SCO ','France'),
  (351,'Morocco',25,'Amin Harit','Marseille ','France'),
  (352,'Morocco',20,'Abdessamad Ezzalzouli','Osasuna ','Spain'),
  (353,'Morocco',22,'Zakaria Aboukhlal','Toulouse ','France'),
  (354,'Morocco',25,'Ilias Chair','Queens Park Rangers ','England'),
  (355,'Morocco',25,'Youssef En-Nesyri','Sevilla ','Spain'),
  (356,'Morocco',24,'Walid Cheddira','S.S.C. Bari ','Italy'),
  (357,'Morocco',31,'Abderrazak Hamdallah','Al Ittihad ','Saudi Arabia'),
  (358,'England',28,'Jordan Pickford','Everton ','England'),
  (359,'England',30,'Nick Pope','Newcastle United ','England'),
  (360,'England',24,'Aaron Ramsdale','Arsenal ','England'),
  (361,'England',28,'John Stone','Manchester City ','England'),
  (362,'England',24,'Trent Alexander-arnold','Liverpool ','England'),
  (363,'England',28,'Eric Dier','Tottenham Hotspur ','England'),
  (364,'England',29,'Conor Coady','Everton ','England'),
  (365,'England',25,'Ben White','Arsenal ','England'),
  (366,'England',27,'Luke Shaw','Manchester United ','England'),
  (367,'England',32,'Kyle Walker','Manchester City ','England'),
  (368,'England',29,'Harry Maguire','Manchester United ','England'),
  (369,'England',32,'Kieran Trippier','Newcastle United ','England'),
  (370,'England',26,'Kalvin Phillips','Manchester City ','England'),
  (371,'England',23,'Declan Rice','West Ham United ','England'),
  (372,'England',22,'Conor Gallagher','Chelsea ','England'),
  (373,'England',19,'Jude Bellingham','Borussia Dortmund ','Germany'),
  (374,'England',32,'Jordan Henderson','Liverpool ','England'),
  (375,'England',23,'Mason Mount','Chelsea ','England'),
  (376,'England',29,'Harry Kane','Tottenham Hotspur ','England'),
  (377,'England',25,'Marcus Rashford','Manchester United ','England'),
  (378,'England',30,'Callum Wilson','Newcastle United ','England'),
  (379,'England',22,'Phil Foden','Manchester City ','England'),
  (380,'England',27,'Jack Grealish','Manchester City ','England'),
  (381,'England',21,'Bukayo Saka','Arsenal ','England'),
  (382,'England',25,'James Maddison','Leicester City ','England'),
  (383,'England',27,'Raheem Sterling','Chelsea ','England'),
  (384,'Poland',31,'Wojciech Szczesny','Juventus ','Italy'),
  (385,'Poland',25,'Bartlomiej Dragowski','Spezia ','Italy'),
  (386,'Poland',31,'Lukasz Skorupski','Bologna ','Italy'),
  (387,'Poland',26,'Jan Bednarek','Aston Villa ','England'),
  (388,'Poland',34,'Kamil Glik','Benevento ','Italy'),
  (389,'Poland',25,'Matty Cash','Aston Villa ','England'),
  (390,'Poland',22,'Jakub Kiwior','Spezia ','Italy'),
  (391,'Poland',24,'Robert Gumny','FC Augsburg ','Germany'),
  (392,'Poland',30,'Bartosz Bereszynski','Sampdoria ','Italy'),
  (393,'Poland',25,'Mateusz Wieteska','Clermont ','France'),
  (394,'Poland',20,'Nicola Zalewski','AS Roma ','Italy'),
  (395,'Poland',34,'Artur Jedrzejczyk','Legia Warsaw ','Poland'),
  (396,'Poland',22,'Michal Skoras','Lech Poznan ','Poland'),
  (397,'Poland',32,'Grzegorz Krychowiak','Al Shabab ','Saudi Arabia'),
  (398,'Poland',28,'Piotr Zielinski','Napoli ','Italy'),
  (399,'Poland',24,'Krystian Bielik','Birmingham ','England'),
  (400,'Poland',34,'Kamil Grosicki','Pogon Szczecin ','Poland'),
  (401,'Poland',27,'Przemyslaw Frankowski','Lens ','France'),
  (402,'Poland',23,'Sebastian Szymanski','Feyenoord ','Netherland'),
  (403,'Poland',27,'Damian Szymanski','AEK Athens ','Greece'),
  (404,'Poland',25,'Szymon Zurkowski','Fiorentina ','Italy'),
  (405,'Poland',20,'Jakub Kaminski','Wolfsburg ','Germany'),
  (406,'Poland',27,'Krzysztof Piatek','Salernitana ','Italy'),
  (407,'Poland',25,'Karol Swiderski','Charlotte ','USA'),
  (408,'Poland',28,'Arkadiusz Milik','Juventus ','Italy'),
  (409,'Poland',34,'Robert Lewandowski','Barcelona ','Spain'),
  (410,'Portugal',29,'Diogo Costa','FC Porto ','Portugal'),
  (411,'Portugal',29,'Jos Sá','Wolverhampton Wanderers ','England'),
  (412,'Portugal',34,'Rui Patrício','AS Roma ','Italy'),
  (413,'Portugal',23,'Diogo Dalot','Manchester United ','England'),
  (414,'Portugal',28,'João Cancelo','Manchester City ','England'),
  (415,'Portugal',31,'Danilo Pereira','Paris Saint-Germain ','France'),
  (416,'Portugal',39,'Pepe','FC Porto ','Portugal'),
  (417,'Portugal',25,'Ruben Dias','Manchester City ','England'),
  (418,'Portugal',19,'António Silva','Benfica ','Portugal'),
  (419,'Portugal',20,'Nuno Mendes','Paris Saint-Germain ','France'),
  (420,'Portugal',28,'Raphael Guerreiro','Borussia Dortmund ','Germany'),
  (421,'Portugal',27,'João Palhinha','Fulham ','England'),
  (422,'Portugal',25,'Rúben Neves','Wolverhampton Wanderers ','England'),
  (423,'Portugal',28,'Bernardo Silva','Manchester City ','England'),
  (424,'Portugal',28,'Bruno Fernandes','Manchester United ','England'),
  (425,'Portugal',29,'João Mário','Benfica ','Portugal'),
  (426,'Portugal',24,'Matheus Nunes','Wolverhampton Wanderers ','England'),
  (427,'Portugal',27,'Otávio Edmilson','FC Porto ','Portugal'),
  (428,'Portugal',22,'Vítor Machado','Paris Saint-Germain ','France'),
  (429,'Portugal',30,'William Carvalho','Real Betis ','Spain'),
  (430,'Portugal',27,'André Silva','RB Leipzig ','Germany'),
  (431,'Portugal',37,'Cristiano Ronaldo','Manchester United ','England'),
  (432,'Portugal',21,'Gonçalo Ramos','Benfica ','Portugal'),
  (433,'Portugal',23,'João Félix','Atlético Madrid ','Spain'),
  (434,'Portugal',23,'Rafael Leão','AC Milan ','Italy'),
  (435,'Portugal',28,'Ricardo Horta','S.C. Braga ','Portugal'),
  (436,'Uruguay',36,'Fernando Muslera','Galatasaray ','Turkey'),
  (437,'Uruguay',29,'Sergio Rochet','Nacional ','Uruguay'),
  (438,'Uruguay',36,'Sebastian Sosa','Independiente ','Argentina'),
  (439,'Uruguay',23,'Ronald Araujo','Barcelona ','Spain'),
  (440,'Uruguay',35,'Martin Caceres','LA Galaxy ','USA'),
  (441,'Uruguay',32,'Sebastian Coates','Sporting Lisbon ','Portugal'),
  (442,'Uruguay',27,'Jose Maria Gimenez','Atlético Madrid ','Spain'),
  (443,'Uruguay',36,'Diego Godin','Velez Sarsfield ','Argentina'),
  (444,'Uruguay',24,'Mathias Olivera','Napoli ','Italy'),
  (445,'Uruguay',25,'Jose Luis Rodriguez','Nacional ','Uruguay'),
  (446,'Uruguay',29,'Guillermo Varela','Flamengo ','Brazil'),
  (447,'Uruguay',24,'Matias Vina','AS Roma ','Italy'),
  (448,'Uruguay',25,'Rodrigo Bentancur','Tottenham Hotspur ','England'),
  (449,'Uruguay',25,'Nicolas De La Cruz','River Plate ','Argentina'),
  (450,'Uruguay',20,'Facundo Pellistri','Manchester United ','England'),
  (451,'Uruguay',26,'Lucas Torreira','Galatasaray ','Turkey'),
  (452,'Uruguay',21,'Manuel Ugarte','Sporting Lisbon ','Portugal'),
  (453,'Uruguay',24,'Federico Valverde','Real Madrid ','Spain'),
  (454,'Uruguay',31,'Matias Vecino','SS Lazio ','Italy'),
  (455,'Uruguay',24,'Agustin Canobbio','Athletico Paranaense ','Brazil'),
  (456,'Uruguay',28,'Giorgian De Arrascaeta','Flamengo ','Brazil'),
  (457,'Uruguay',26,'Maxi Gomez','Trabzonspor ','Turkey'),
  (458,'Uruguay',35,'Edinson Cavani','Valencia ','Spain'),
  (459,'Uruguay',23,'Darwin Nunez','Liverpool ','England'),
  (460,'Uruguay',35,'Luis Suarez','Nacional ','Uruguay'),
  (461,'Uruguay',22,'Facundo Torres','Orlando City ','USA'),
  (462,'Senegal',30,'Édouard Mendy','Chelsea ','England'),
  (463,'Senegal',29,'Alfred Gomis','Rennes ','France'),
  (464,'Senegal',27,'Seny Dieng','Queens Park Rangers ','England'),
  (465,'Senegal',31,'Kalidou Koulibaly','Chelsea ','England'),
  (466,'Senegal',26,'Abdou Diallo','RB Leipzig ','Germany'),
  (467,'Senegal',29,'Youssouf Sabaly','Real Betis ','Spain'),
  (468,'Senegal',25,'Fodé Ballo-Touré','AC Milan ','Italy'),
  (469,'Senegal',27,'Pape Abou Cisse','Olympiacos ','Greece'),
  (470,'Senegal',23,'Ismail Jakobs','AS Monaco ','France'),
  (471,'Senegal',21,'Formose Mendy','Amiens SC ','France'),
  (472,'Senegal',33,'Idrissa Gueye','Everton ','England'),
  (473,'Senegal',32,'Cheikhou Kouyaté','Nottingham Forest ','England'),
  (474,'Senegal',30,'Nampalys Mendy','Leicester City ','England'),
  (475,'Senegal',23,'Krepin Diatta','AS Monaco ','France'),
  (476,'Senegal',23,'Pape Gueye','Marseille ','France'),
  (477,'Senegal',20,'Pape Matar Sarr','Tottenham Hotspur ','England'),
  (478,'Senegal',28,'Pathe Ciss','Rayo Vallecano ','Spain'),
  (479,'Senegal',27,'Nama Moustapha','Pafos FC ','Greece'),
  (480,'Senegal',25,'Loum Ndiaye','Reading ','England'),
  (481,'Senegal',30,'Sadio Mane','Bayern Munchen ','Germany'),
  (482,'Senegal',24,'Ismaila Sarr','Watford ','England'),
  (483,'Senegal',25,'Boulye Dia','Salernitana ','Italy'),
  (484,'Senegal',20,'Bamba Dieng','Marseille ','France'),
  (485,'Senegal',29,'Famara Diedhiou','Alanyaspor ','Turkey'),
  (486,'Senegal',21,'Nicolas Jackson','Villarreal ','Spain'),
  (487,'Senegal',22,'Iliman Ndiaye','Sheffield United ','England'),
  (488,'Netherland',24,'Justin Bijlow','Feyenoord ','Netherland'),
  (489,'Netherland',28,'Andries Noppert','Heerenveen ','Netherland'),
  (490,'Netherland',39,'Remko Pasveer','Ajax Amsterdam ','Netherland'),
  (491,'Netherland',27,'Nathan Aké','Manchester City ','England'),
  (492,'Netherland',31,'Virgil van Dijk','Liverpool ','England'),
  (493,'Netherland',23,'Matthijs de Ligt','Bayern Munchen ','Germany'),
  (494,'Netherland',21,'Jurriën Timber','Ajax Amsterdam ','Netherland'),
  (495,'Netherland',30,'Stefan de Vrij','Inter Milan ','Italy'),
  (496,'Netherland',23,'Tyrell Malacia','Manchester United ','England'),
  (497,'Netherland',32,'Daley Blind','Ajax Amsterdam ','Netherland'),
  (498,'Netherland',21,'Jeremie Frimpong','Bayer Leverkusen ','Germany'),
  (499,'Netherland',26,'Denzel Dumfries','Inter Milan ','Italy'),
  (500,'Netherland',30,'Steven Berghuis','Ajax Amsterdam ','Netherland'),
  (501,'Netherland',25,'Frenkie de Jong','Barcelona ','Spain'),
  (502,'Netherland',31,'Marten de Roon','Atalanta ','Italy'),
  (503,'Netherland',24,'Teun Koopmeiners','Atalanta ','Italy'),
  (504,'Netherland',29,'Davy Klaassen','Ajax Amsterdam ','Netherland'),
  (505,'Netherland',19,'Xavi Simons','PSV Eindhoven ','Netherland'),
  (506,'Netherland',20,'Kenneth Taylor','Ajax Amsterdam ','Netherland'),
  (507,'Netherland',25,'Steven Bergwijn','Ajax Amsterdam ','Netherland'),
  (508,'Netherland',23,'Cody Gakpo','PSV Eindhoven ','Netherland'),
  (509,'Netherland',28,'Vincent Janssen','Antwerp ','Belgium'),
  (510,'Netherland',28,'Memphis Depay','Barcelona ','Spain'),
  (511,'Netherland',32,'Luuk de Jong','PSV Eindhoven ','Netherland'),
  (512,'Netherland',30,'Wout Weghorst','Besiktas ','Turkey'),
  (513,'Netherland',23,'Noa Lang','Club Brugge ','Belgium'),
  (514,'Spain',25,'Unai Simón','Athletic Bilbao ','Spain'),
  (515,'Spain',24,'Robert Sánchez','Brighton & Hove Albion ','England'),
  (516,'Spain',27,'David Raya','Brentford ','England'),
  (517,'Spain',30,'Dani Carvajal','Real Madrid ','Spain'),
  (518,'Spain',33,'César Azpilicueta','Chelsea ','England'),
  (519,'Spain',21,'Eric García','Barcelona ','Spain'),
  (520,'Spain',22,'Hugo Guillamón','Valencia ','Spain'),
  (521,'Spain',25,'Pau Torres','Villarreal ','Spain'),
  (522,'Spain',28,'Aymeric Laporte','Manchester City ','England'),
  (523,'Spain',33,'Jordi Alba','Barcelona ','Spain'),
  (524,'Spain',27,'José Gayà','Valencia ','Spain'),
  (525,'Spain',34,'Sergio Busquets','Barcelona ','Spain'),
  (526,'Spain',26,'Rodri','Manchester City ','England'),
  (527,'Spain',18,'Gavi','Barcelona ','Spain'),
  (528,'Spain',25,'Carlos Soler','Paris Saint-Germain ','France'),
  (529,'Spain',27,'Marcos Llorente','Atlético Madrid ','Spain'),
  (530,'Spain',19,'Pedri','Barcelona ','Spain'),
  (531,'Spain',30,'Koke','Atlético Madrid ','Spain'),
  (532,'Spain',22,'Ferran Torres','Barcelona ','Spain'),
  (533,'Spain',20,'Nico Williams','Athletic Bilbao ','Spain'),
  (534,'Spain',20,'Yeremy Pino','Villarreal ','Spain'),
  (535,'Spain',30,'Álvaro Morata','Atlético Madrid ','Spain'),
  (536,'Spain',26,'Marco Asensio','Real Madrid ','Spain'),
  (537,'Spain',30,'Pablo Sarabia','Paris Saint-Germain ','France'),
  (538,'Spain',24,'Dani Olmo','RB Leipzig ','Germany'),
  (539,'Spain',20,'Ansu Fati','Barcelona ','Spain'),
  (540,'Serbia',30,'Marko Dmitrovic','Sevilla ','Spain'),
  (541,'Serbia',25,'Vanja Milinkovic-Savic','Torino ','Italy'),
  (542,'Serbia',27,'Predrag Rajkovic','RCD Mallorca ','Spain'),
  (543,'Serbia',32,'Stefan Mitrovic','Getafe ','Spain'),
  (544,'Serbia',21,'Strahinja Pavlovic','Red Bull Salzburg ','Austria'),
  (545,'Serbia',27,'Milos Veljkovic','Werder Bremen ','Germany'),
  (546,'Serbia',31,'Filip Mladenovic','Legia Warsaw ','Poland'),
  (547,'Serbia',21,'Strahinja Erakovic','Red Star Belgrade ','Serbia'),
  (548,'Serbia',26,'Srdan Babic','Almeria ','Spain'),
  (549,'Serbia',25,'Nikola Milenkovic','Fiorentina ','Italy'),
  (550,'Serbia',29,'Filip Kostic','Juventus ','Italy'),
  (551,'Serbia',27,'Nemanja Maksimovic','Getafe ','Spain'),
  (552,'Serbia',26,'Sasa Lukic','Torino ','Italy'),
  (553,'Serbia',26,'Andrija Zivkovic','PAOK ','Greece'),
  (554,'Serbia',32,'Darko Lazovic','Verona ','Italy'),
  (555,'Serbia',27,'Sergej Milinkovic-Savic','SS Lazio ','Italy'),
  (556,'Serbia',30,'Nemandja Gudelj','Sevilla ','Spain'),
  (557,'Serbia',26,'Marko Grujic','Porto ','Portugal'),
  (558,'Serbia',24,'Uros Racic','Braga ','Portugal'),
  (559,'Serbia',21,'Ivan Ilic','Verona ','Italy'),
  (560,'Serbia',28,'Aleksandar Mitrovic','Fulham ','England'),
  (561,'Serbia',24,'Luka Jovic','Fiorentina ','Italy'),
  (562,'Serbia',22,'Dusan Vlahovic','Juventus ','Italy'),
  (563,'Serbia',26,'Nemanja Radonjic','Torino ','Italy'),
  (564,'Serbia',30,'Filip Duricic','Sampdoria ','Italy'),
  (565,'Serbia',33,'Dušan Tadi?','Ajax Amsterdam ','Netherland'),
  (566,'Argentina',30,'Emiliano Martínez','Aston Villa ','England'),
  (567,'Argentina',30,'Geronimo Rulli','Villarreal ','Spain'),
  (568,'Argentina',36,'Franco Armani','River Plate ','Argentina'),
  (569,'Argentina',24,'Nahuel Molina','Atlético Madrid ','Spain'),
  (570,'Argentina',25,'Gonzalo Montiel','Sevilla ','Spain'),
  (571,'Argentina',24,'Cristian Romero','Tottenham Hotspur ','England'),
  (572,'Argentina',31,'Germán Pezzella','Real Betis ','Spain'),
  (573,'Argentina',34,'Nicolás Otamendi','Benfica ','Portugal'),
  (574,'Argentina',24,'Lisandro Martinez','Manchester United ','England'),
  (575,'Argentina',31,'Marcos Acuña','Sevilla ','Spain'),
  (576,'Argentina',30,'Nicolás Tagliafico','Lyon ','France'),
  (577,'Argentina',24,'Juan Foyth','Villarreal ','Spain'),
  (578,'Argentina',28,'Rodrigo De Paul','Atlético Madrid ','Spain'),
  (579,'Argentina',28,'Leandro Paredes','Juventus ','Italy'),
  (580,'Argentina',23,'Alexis Mac Allister','Brighton & Hove Albion ','England'),
  (581,'Argentina',28,'Guido Rodríguez','Real Betis ','Spain'),
  (582,'Argentina',34,'Alejandro Gómez','Sevilla ','Spain'),
  (583,'Argentina',21,'Enzo Fernandez','Benfica ','Portugal'),
  (584,'Argentina',24,'Exequiel Palacios','Bayer Leverkusen ','Germany'),
  (585,'Argentina',34,'Angel Di Maria','Juventus ','Italy'),
  (586,'Argentina',25,'Lautaro Martínez','Inter Milan ','Italy'),
  (587,'Argentina',22,'Julián lvarez','Manchester City ','England'),
  (588,'Argentina',24,'Nicolás González','Fiorentina ','Italy'),
  (589,'Argentina',28,'Joaquín Correa','Inter Milan ','Italy'),
  (590,'Argentina',28,'Paulo Dybala','AS Roma ','Italy'),
  (591,'Argentina',34,'Lionel Messi','Paris Saint-Germain ','France'),
  (592,'Saudi Arabia',25,'Mohammed Al Rubaie','Al-Ahli ','Saudi Arabia'),
  (593,'Saudi Arabia',31,'Mohammed Al-Owais','Al-Hilal ','Saudi Arabia'),
  (594,'Saudi Arabia',22,'Nawaf Al-Aqidi','Al-Nassr ','Saudi Arabia'),
  (595,'Saudi Arabia',30,'Yasser Al-Shahrani','Al-Hilal ','Saudi Arabia'),
  (596,'Saudi Arabia',32,'Ali Al-Bulaihi','Al-Hilal ','Saudi Arabia'),
  (597,'Saudi Arabia',25,'Abdulelah Al-Amri','Al-Nassr ','Saudi Arabia'),
  (598,'Saudi Arabia',29,'Abdullah Madu','Al-Nassr ','Saudi Arabia'),
  (599,'Saudi Arabia',23,'Hassan Tambakti','Al-Shabab ','Saudi Arabia'),
  (600,'Saudi Arabia',28,'Sultan Al-Ghanam','Al-Nassr ','Saudi Arabia'),
  (601,'Saudi Arabia',30,'Mohammed Al-Breik','Al-Hilal ','Saudi Arabia'),
  (602,'Saudi Arabia',23,'Saud Abdulhamid','Al-Hilal ','Saudi Arabia'),
  (603,'Saudi Arabia',31,'Salman Al-Faraj','Al-Hilal ','Saudi Arabia'),
  (604,'Saudi Arabia',29,'Riyadh Sharahili','Abha ','Saudi Arabia'),
  (605,'Saudi Arabia',25,'Ali Al-Hassan','Al-Nassr ','Saudi Arabia'),
  (606,'Saudi Arabia',28,'Mohamed Kanno','Al-Hilal ','Saudi Arabia'),
  (607,'Saudi Arabia',28,'Abdulelah Al-Malki','Al-Hilal ','Saudi Arabia'),
  (608,'Saudi Arabia',25,'Sami Al-Najei','Al-Nassr ','Saudi Arabia'),
  (609,'Saudi Arabia',30,'Abdullah Otayf','Al-Hilal ','Saudi Arabia'),
  (610,'Saudi Arabia',31,'Nasser Al-Dawsari','Al-Hilal ','Saudi Arabia'),
  (611,'Saudi Arabia',27,'Abdulrahman Al-Aboud','Ittihad ','Saudi Arabia'),
  (612,'Saudi Arabia',31,'Salem Al-Dawsari','Al-Hilal ','Saudi Arabia'),
  (613,'Saudi Arabia',30,'Hattan Bahebri','Al-Shabab ','Saudi Arabia'),
  (614,'Saudi Arabia',28,'Fahad Al-Muwallad','Al-Shabab ','Saudi Arabia'),
  (615,'Saudi Arabia',28,'Haitham Asiri','Al-Ahly ','Saudi Arabia'),
  (616,'Saudi Arabia',29,'Saleh Al-Shehri','Al-Hilal ','Saudi Arabia'),
  (617,'Saudi Arabia',22,'Firas Al-Buraikan','Al-Fateh ','Saudi Arabia'),
  (618,'Qatar',32,'Saad Alsheeb','Al-Sadd ','Qatar'),
  (619,'Qatar',24,'Meshaal Barsham','Al-Sadd ','Qatar'),
  (620,'Qatar',26,'Yousef Hassan','Al-Gharafa ','Qatar'),
  (621,'Qatar',32,'Pedro Miguel','Al-Sadd ','Qatar'),
  (622,'Qatar',29,'Musaab Khidir','Al-Sadd ','Qatar'),
  (623,'Qatar',24,'Tarek Salman','Al-Sadd ','Qatar'),
  (624,'Qatar',24,'Bassam Al-Rawi','Al-Duhail ','Qatar'),
  (625,'Qatar',32,'Boualem Khoukhi','Al-Sadd ','Qatar'),
  (626,'Qatar',29,'Abdelkarim Hassan','Al-Sadd ','Qatar'),
  (627,'Qatar',23,'Homam Ahmed','Al-Gharafa ','Qatar'),
  (628,'Qatar',20,'Jassem Gaber','Al-Arabi ','Qatar'),
  (629,'Qatar',29,'Ali Assadalla','Al-Sadd ','Qatar'),
  (630,'Qatar',26,'Assim Madabo','Al-Duhail ','Qatar'),
  (631,'Qatar',23,'Mohammed Waad','Al-Sadd ','Qatar'),
  (632,'Qatar',26,'Salem Al-Hajri','Al-Sadd ','Qatar'),
  (633,'Qatar',21,'Moustafa Tarek','Al-Sadd ','Qatar'),
  (634,'Qatar',32,'Karim Boudiaf','Al-Duhail ','Qatar'),
  (635,'Qatar',32,'Abdelaziz Hatim','Al-Rayyan ','Qatar'),
  (636,'Qatar',32,'Ismail Mohamad','Al-Duhail ','Qatar'),
  (637,'Qatar',21,'Naif Alhadhrami','Al-Rayyan ','Qatar'),
  (638,'Qatar',29,'Ahmed Alaaeldin','Al-Gharafa ','Qatar'),
  (639,'Qatar',31,'Hassan Al-Haydos','Al-Sadd ','Qatar'),
  (640,'Qatar',23,'Khalid Muneer','Al-Wakrah ','Qatar'),
  (641,'Qatar',25,'Akram Afif','Al-Sadd ','Qatar'),
  (642,'Qatar',26,'Almoez Ali','Al-Duhail ','Qatar'),
  (643,'Qatar',28,'Mohamed Muntari','Al-Duhail ','Qatar'),
  (644,'South Korea',32,'Kim Seung-Gyu','Al-Shabab ','Saudi Arabia'),
  (645,'South Korea',31,'Jo Hyeon-Woo','Ulsan Hyundai ','South Korea'),
  (646,'South Korea',25,'Song Bum-Keun','Jeonbuk Hyundai Motors ','South Korea'),
  (647,'South Korea',25,'Kim Min-jae','Napoli ','Italy'),
  (648,'South Korea',32,'Kim Young-gwon','Ulsan Hyundai ','South Korea'),
  (649,'South Korea',32,'Kwon Kyung-won','Gamba Osaka ','Japan'),
  (650,'South Korea',27,'Kim Moon-hwan','Jeonbuk Hyundai Motors ','South Korea'),
  (651,'South Korea',24,'Yoon Jong-gyu','FC Seoul ','South Korea'),
  (652,'South Korea',32,'Hong Chul','Daegu FC ','South Korea'),
  (653,'South Korea',25,'Cho Yu-Min','Daejon Hana Citizen ','South Korea'),
  (654,'South Korea',33,'Kim Tae-Gwan','Ulsan Hyundai ','South Korea'),
  (655,'South Korea',30,'Kim Jin-Su','Jeonbuk Hyundai Motors ','South Korea'),
  (656,'South Korea',32,'Jung Woo-Young','Al-Sadd ','Qatar'),
  (657,'South Korea',30,'Son Jun-Ho','Shandong Taisan ','China'),
  (658,'South Korea',25,'Paik Seung-Ho','Jeonbuk Hyundai Motors ','South Korea'),
  (659,'South Korea',26,'Hwang In-Beom','Olympiacos ','Greece'),
  (660,'South Korea',30,'Lee Jae-Sung','Mainz 05 ','Germany'),
  (661,'South Korea',28,'Kwon Chang-Hoon','Gimcheon Sangmu ','South Korea'),
  (662,'South Korea',23,'Jeong Woo-Yeong','FC Freiburg ','Germany'),
  (663,'South Korea',23,'Lee Kang-In','Mallorca ','Spain'),
  (664,'South Korea',23,'Song Min-Kyu','Jeonbuk Hyundai Motors ','South Korea'),
  (665,'South Korea',30,'Son Heung-Min','Tottenham Hotspur ','England'),
  (666,'South Korea',26,'Na Sang-Ho','FC Seoul ','South Korea'),
  (667,'South Korea',26,'Hwang Hee-Chan','Wolverhampton Wanderers ','England'),
  (668,'South Korea',30,'Hwang Ui-Jo','Olympiacos ','Greece'),
  (669,'South Korea',24,'Cho Gue-Sung','Jeonbuk Hyundai Motors ','South Korea'),
  (670,'Iran',29,'Amir Abedzadeh','Ponferradina ','Spain'),
  (671,'Iran',30,'Alireza Beiranvand','Persepolis ','Iran'),
  (672,'Iran',30,'Hossein Hosseini','Esteghlal ','Iran'),
  (673,'Iran',27,'Payam Niazmand','Persepolis ','Iran'),
  (674,'Iran',34,'Rouzbeh Cheshmi','Esteghlal ','Iran'),
  (675,'Iran',30,'Ehsan Hajsafi','AEK Athens ','Greece'),
  (676,'Iran',26,'Majid Hosseini','Kayserispor ','Turkey'),
  (677,'Iran',25,'Abolfazl Jalali','Esteghlal ','Iran'),
  (678,'Iran',27,'Hossein Kanaani','Al Ahli ','Qatar'),
  (679,'Iran',25,'Shojae Khalilzadeh','Al Ahli ','Qatar'),
  (680,'Iran',28,'Milad Mohammadi','AEK Athens ','Greece'),
  (681,'Iran',27,'Sadegh Moharrami','Dinamo Zagreb ','Croatia'),
  (682,'Iran',26,'Morteza Pouraliganji','Persepolis ','Iran'),
  (683,'Iran',32,'Ramin Rezaeian','Sepahan ','Iran'),
  (684,'Iran',34,'Vahid Amiri','Persepolis ','Iran'),
  (685,'Iran',26,'Saeid Ezatolahi','Vejle ','Denmark'),
  (686,'Iran',29,'Saman Ghoddos','Brentford ','England'),
  (687,'Iran',26,'Ali Gholizadeh','Charleroi ','Belgium'),
  (688,'Iran',29,'Alireza Jahanbakhsh','Feyenoord ','Netherland'),
  (689,'Iran',28,'Ali Karimi','Kayserispor ','Turkey'),
  (690,'Iran',29,'Ahmad Noorollahi','Shabab Al Ahli ','UAE'),
  (691,'Iran',28,'Mehdi Torabi','Persepolis','Iran'),
  (692,'Iran',28,'Karim Ansarifard','Omonia Nicosia','Cyprus'),
  (693,'Iran',27,'Sardar Azmoun','Bayer Leverkusen ','Germany'),
  (694,'Iran',30,'Mehdi Taremi','Porto ','Portugal'),
  (695,'Tunisia',25,'Aymen Dahmen','Club Sportif Sfaxien ','Tunisia'),
  (696,'Tunisia',27,'Mouez Hassan','Club Africain ','Tunisia'),
  (697,'Tunisia',27,'Bechir Ben Said','US Monastir ','Tunisia'),
  (698,'Tunisia',38,'Aymen Mathlouthi','Etoile du Sahel ','Tunisia'),
  (699,'Tunisia',28,'Ali Abdi','Caen ','France'),
  (700,'Tunisia',26,'Mohamed Drager','FC Luzern ','Switzerland'),
  (701,'Tunisia',32,'Ali Maaloul','Al-Ahly ','Egypt'),
  (702,'Tunisia',27,'Wajdi Kechrida','Atromitos ','Greece'),
  (703,'Tunisia',27,'Nader Ghandri','Club Africain ','Tunisia'),
  (704,'Tunisia',29,'Yassine Meriah','Esperance ','Tunisia'),
  (705,'Tunisia',32,'Bilel Ifa','Kuwait FC ','Kuwait'),
  (706,'Tunisia',27,'Dylan Bronn','Salernitana ','Italy'),
  (707,'Tunisia',24,'Montassar Talbi','Lorient ','France'),
  (708,'Tunisia',27,'Ellyes Skhiri','FC Cologne ','Germany'),
  (709,'Tunisia',28,'Ghaylen Chaalali','Esperance ','Tunisia'),
  (710,'Tunisia',25,'Aissa Laidouni','Ferencvaros ','Hungary'),
  (711,'Tunisia',23,'Mohamed Ali Ben Romdhane','Esperance ','Tunisia'),
  (712,'Tunisia',30,'Ferjani Sassi','Al-Duhail','Qatar'),
  (713,'Tunisia',19,'Hannibal Mejbri','Birmingham ','England'),
  (714,'Tunisia',32,'Youssef Msakni','Al-Arabi SC ','Qatar'),
  (715,'Tunisia',29,'Seifeddine Jaziri','Zamalek ','Egypt'),
  (716,'Tunisia',30,'Naim Sliti','Ettifaq ','Saudi Arabia'),
  (717,'Tunisia',30,'Issam Jebali','Odense Boldklub ','Denmark'),
  (718,'Tunisia',30,'Taha Yassine Khenissi','Kuwait SC ','Kuwait'),
  (719,'Tunisia',21,'Anis Ben Slimane','Brondby FK ','Denmark'),
  (720,'Tunisia',31,'Wahbi Khazri','Montpellier ','France'),
  (721,'Canada',35,'Milan Borjan','Red Star Belgrade ','Serbia'),
  (722,'Canada',25,'Dayne St. Claire','Minnesota United ','USA'),
  (723,'Canada',25,'James Pantemis','CF Montréal ','Canada'),
  (724,'Canada',22,'Alphonso Davies','Bayern Munchen ','Germany'),
  (725,'Canada',35,'Steven Vitoria','Chaves ','Portugal'),
  (726,'Canada',27,'Sam Adekugbe','Hatayspor ','Turkey'),
  (727,'Canada',27,'Richie Laryea','Toronto FC ','USA'),
  (728,'Canada',24,'Alistair Johnston','CF Montreal ','Canada'),
  (729,'Canada',25,'Kamal Miller','CF Montreal ','Canada'),
  (730,'Canada',24,'Derek Cornelius','Panetolikos ','Greece'),
  (731,'Canada',26,'Joel Waterman','CF Montreal ','Canada'),
  (732,'Canada',28,'Samuel Piette','CF Montreal ','Canada'),
  (733,'Canada',27,'Mark-Anthony Kaye','Toronto FC ','USA'),
  (734,'Canada',25,'Stephen Eustaquio','Porto ','Portugal'),
  (735,'Canada',22,'Ismael Kone','CF Montreal ','Canada'),
  (736,'Canada',39,'Atiba Hutchinson','Besiktas ','Turkey'),
  (737,'Canada',24,'Liam Fraser','Deinze ','Belgium'),
  (738,'Canada',30,'Jonathan Osorio','Toronto FC ','USA'),
  (739,'Canada',32,'David Wotherspoon','St Johnstone ','Scotland'),
  (740,'Canada',32,'Junior Hoilett','Reading ','England'),
  (741,'Canada',27,'Cyle Larin','Club Brugge ','Belgium'),
  (742,'Canada',22,'Jonathan David','Lille ','France'),
  (743,'Canada',29,'Lucas Cavallini','Vancouver Whitecaps ','Canada'),
  (744,'Canada',23,'Tajon Buchanan','Club Brugge ','Belgium'),
  (745,'Canada',23,'Liam Millar','Basel ','Switzerland'),
  (746,'Canada',24,'Ike Ugbo','Troyes ','France'),
  (747,'Mexico',37,'Guillermo Ochoa','Club America ','Mexico'),
  (748,'Mexico',40,'Alfredo Talavera','Juarez ','Mexico'),
  (749,'Mexico',35,'Rodolfo Cota','Leon ','Mexico'),
  (750,'Mexico',31,'Nestor Araujo','Club America ','Mexico'),
  (751,'Mexico',25,'Cesar Montes','Monterrey ','Mexico'),
  (752,'Mexico',24,'Johan Vasquez','Cremonese ','Mexico'),
  (753,'Mexico',24,'Gerardo Arteaga','K.R.C. Genk ','Belgium'),
  (754,'Mexico',34,'Hector Moreno','Monterrey ','Mexico'),
  (755,'Mexico',24,'Jorge Sanchez','Ajax Amsterdam ','Netherland'),
  (756,'Mexico',28,'Jesus Gallardo','Monterrey ','Mexico'),
  (757,'Mexico',23,'Kevin Alvarez','Pachuca ','Mexico'),
  (758,'Mexico',25,'Edson Alvarez','Ajax Amsterdam ','Netherland'),
  (759,'Mexico',27,'Luis Romo','Monterrey ','Mexico'),
  (760,'Mexico',25,'Carlos Rodriguez','Cruz Azul ','Mexico'),
  (761,'Mexico',27,'Erick Gutierrez','PSV Eindhoven ','Netherland'),
  (762,'Mexico',32,'Hector Herrera','Houston Dynamo ','USA'),
  (763,'Mexico',26,'Luis Chavez','Pachuca ','Mexico'),
  (764,'Mexico',36,'Andres Guardado','Real Betis ','Spain'),
  (765,'Mexico',26,'Orbelin Pineda','AEK Athens ','Greece'),
  (766,'Mexico',31,'Raul Jimenez','Wolverhampton Wanderers ','England'),
  (767,'Mexico',24,'Alexis Vega','Guadalajara ','Mexico'),
  (768,'Mexico',31,'Rogelio Funes Mori','Monterrey ','Mexico'),
  (769,'Mexico',29,'Henry Martin','Club America ','Mexico'),
  (770,'Mexico',27,'Hirving Lozano','Napoli ','Italy'),
  (771,'Mexico',24,'Roberto Alvarado','Guadalajara ','Mexico'),
  (772,'Mexico',25,'Uriel Antuna','Cruz Azul ','Mexico'),
  (773,'Ghana',25,'Lawrence Ati-Zigi','St. Gallen ','Switzerland'),
  (774,'Ghana',23,'Abdul Manaf Nurudeen','Eupen ','Belgium'),
  (775,'Ghana',19,'Ibrahim Danlad','Asante Kotoko ','Ghana'),
  (776,'Ghana',27,'Daniel Amartey','Leicester City ','England'),
  (777,'Ghana',28,'Abdul-Rahman Baba','Reading ','England'),
  (778,'Ghana',28,'Alexander Djiku','Strasbourg ','France'),
  (779,'Ghana',27,'Joseph Aidoo','Celta De Vigo ','Spain'),
  (780,'Ghana',24,'Gideon Mensah','Bordeaux ','France'),
  (781,'Ghana',34,'Denis Odoi','Club Brugge ','Belgium'),
  (782,'Ghana',22,'Tariq Lamptey','Brighton & Hove Albion ','England'),
  (783,'Ghana',22,'Alidu Seidu','Clermont ','France'),
  (784,'Ghana',23,'Mohammed Salisu','Southampton ','England'),
  (785,'Ghana',22,'Mohammed Kudus','Ajax Amsterdam ','Netherland'),
  (786,'Ghana',29,'Thomas Partey','Arsenal ','England'),
  (787,'Ghana',32,'Andre Ayew','Al Saad ','Qatar'),
  (788,'Ghana',25,'Elisha Owusu','Gent ','Belgium'),
  (789,'Ghana',26,'Daniel-Kofi Kyereh','St Pauli ','Germany'),
  (790,'Ghana',21,'Daniel Afriyie Barnieh','Hearts of Oak ','Ghana'),
  (791,'Ghana',22,'Salis Abdul Samed','Lens ','France'),
  (792,'Ghana',22,'Antoine Semenyo','Bristol City ','England'),
  (793,'Ghana',18,'Abdul Fatawu Issahaku','Sporting Lisbon ','Portugal'),
  (794,'Ghana',31,'Jordan Ayew','Crystal Palace ','England'),
  (795,'Ghana',20,'Kamaldeen Sulemana','Rennes ','France'),
  (796,'Ghana',23,'Osman Bukari','Red Star Belgrade ','Serbia'),
  (797,'Ghana',28,'Inaki Williams','Athletic Bilbao ','Spain'),
  (798,'Ghana',22,'Kamal Sowah','Club Brugge ','Belgium'),
  (799,'Ecuador',35,'Alexander Domínguez','LDU Quito ','Ecuador'),
  (800,'Ecuador',35,'Hernán Galíndez','Aucas ','Ecuador'),
  (801,'Ecuador',22,'Moisés Ramirez','Independiente del Valle ','Ecuador'),
  (802,'Ecuador',24,'Angelo Preciado','K.R.C. Genk ','Belgium'),
  (803,'Ecuador',24,'Pervis Estupiñán','Brighton & Hove Albion ','England'),
  (804,'Ecuador',23,'Diego Palacios','LA Galaxy ','USA'),
  (805,'Ecuador',20,'Piero Hincapié','Bayer Leverkusen ','Germany'),
  (806,'Ecuador',22,'Jackson Porozo','Troyes ','France'),
  (807,'Ecuador',31,'Robert Arboleda','São Paulo ','Brazil'),
  (808,'Ecuador',28,'Xavier Arreaga','Seattle Sounders ','USA'),
  (809,'Ecuador',25,'Félix Torres','Santos Laguna ','Mexico'),
  (810,'Ecuador',21,'William Pacho','Antwerp ','Belgium'),
  (811,'Ecuador',27,'Carlos Gruezo','Augsburg ','Germany'),
  (812,'Ecuador',25,'Jhegson Méndez','LA Galaxy ','USA'),
  (813,'Ecuador',23,'José Cifuentes','LA Galaxy ','USA'),
  (814,'Ecuador',24,'Alan Franco','Talleres ','Argentina'),
  (815,'Ecuador',21,'Moisés Caicedo','Brighton & Hove Albion ','England'),
  (816,'Ecuador',34,'Ángel Mena','León ','Mexico'),
  (817,'Ecuador',28,'Ayrton Preciado','Santos Laguna ','Mexico'),
  (818,'Ecuador',22,'Gonzalo Plata','Real Valladolid ','Spain'),
  (819,'Ecuador',28,'Romario Ibarra','Pachuca ','Mexico'),
  (820,'Ecuador',20,'Jeremy Sarmiento','Brighton & Hove Albion ','England'),
  (821,'Ecuador',33,'Enner Valencia','Fenerbahçe ','Turkey'),
  (822,'Ecuador',26,'Micheal Estrada','Cruz Azul ','Mexico'),
  (823,'Ecuador',23,'Djorkaeff Reasco','Newell’s Old Boys ','Argentina'),
  (824,'Ecuador',22,'Kevin Rodríguez','Imbabura ','Ecuador');

SELECT * FROM SquadDetails;
